apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: 192.168.137.101:6443
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: svc-devops
              servicePort: 8090